### ISSUE TITLE
Remove dependency on nose (port to pytest)

### ISSUE THREAD

**Issue by mcepl** [ipython/ipython_genutils#17]
I am a maintainer of Python packages in openSUSE, and I am on my crusade of eliminating nose1 from our distribution. When I look at its repository on https://github.com/nose-devs/nose, the last release 1.3.7 was on 2 Jun 2015, and even the last commit on the master branch was on 4 Mar 2016.

[This patch](https://github.com/ipython/ipython_genutils/files/5798579/denose.patch.txt) eliminates dependency on nose, which has been unnecessary for a long time. Resulting test suite depends on pytest, which is currently perfectly developed and maintained.

**Comment by Carreau** [comment]
Many thanks for working on this. I'll try to integrate this and might do a release. Thought it may take some time. Another possibility would be to finish removing usage of this package from the dependees.

**Comment by mcepl** [comment]
I work for SUSE, which means we are working on hundreds of packages, so I cannot concentrate on one particular package for too long … my current enemy is nose, and so I eliminate it. Concerning dependees, given this whole package has been already deprecated, it seems weird how stubbornly it refuses to die.

**Comment by Carreau** [comment]
> Concerning dependees, given this whole package has been already deprecated, it seems weird how stubbornly it refuses to die.

Sorry, this was not a comment for you to do this; I am a maintainer of (all?) the direct dependees that use ipython_genutils, and more a comment that I might go the route of removing ipython_genutils as a dependencies from those (so you can drop ipython_genutils from your list of packages) instead of publishing a new release if `ipython_genutils`. I might also do both depending on the timeline.

Updating the dependees might also be a better route as some of them still require nose1 IIRC (which is one of the things i've also been getting rid of progressively).

To be clearer, I have commit rights to remove and publish new version of the following packages to not use ipython_genutils:

ipython
ipykernel
ipyparallel
ipython_genutils
jupyter_client
jupyter_console
jupyter_core
jupyter_server
nbconvert
nbformat
notebook
qtconsole
traitlets

A few of those also directly use nose, and I'll try to remove nose usage as well, but will take time.

**Comment by mcepl** [comment]
Looking through [openSUSE packages](https://build.opensuse.org/project/show/devel:languages:python:jupyter) and it seems to me that some packages you mentioned really don’t require nose:

- [x] python-ipython testing still depends on nose
- [x] python-ipykernel testing still depends on nose
- [x] python-ipyparallel runs pytest without any patch
- [x] python-ipython_genutils pytest with this patch
- [x] python-jupyter_client pytest without any patch
- [x] python-jupyter_console pytest with the patch from https://github.com/jupyter/jupyter_console/pull/230
- [x] python-jupyter_core running with pytest
- [x] python-jupyter_server running with pytest
- [x] python-nbconvert runs with pytest, with patch from https://github.com/jupyter/nbconvert/issues/1526
- [x] python-nbformat uses pytest even without any patching ([we have excluded](https://build.opensuse.org/package/view_file/devel:languages:python:jupyter/python-nbformat/python-nbformat.spec?expand=1) two test classes, but hopefully at least partially meaningful test suite remains)
- [x] python-notebook using pytest with patch sent upstream as https://github.com/jupyter/notebook/issues/5826
- [x] python-qtconsole pytest w/o patch (with some tests skipped according to https://github.com/jupyter/qtconsole/issues/443)
- [x] python-traitlets ditto (running `pushd doc && pytest -v ../traitlets/tests`)

**Comment by Carreau** [comment]
Yeah, my concern is that some of the test are skipped on pytest. I'll see what I can do to help with this migration. Feel free to drop links to upstream issue I'm happy to mention there when the upstream patches have been merged or releases have been done.

**Comment by mcepl** [comment]
@Carreau https://github.com/ipython/ipython/pull/12840

**Comment by Carreau** [comment]
https://github.com/jupyter/jupyter_client/pull/622 might also help to remove genutils as a dependencies of Jupyter_client.

**Comment by opoplawski** [comment]
Any more progress here?  We're probably not going to introduce nose into EPEL9.  Still a number of packages using ipython_genutils.

**Comment by mcepl** [comment]
> Any more progress here? We're probably not going to introduce nose into EPEL9. Still a number of packages using ipython_genutils.

https://build.opensuse.org/package/view_file/devel:languages:python:jupyter/python-ipython_genutils/denose.patch?expand=1
works still just fine for us.

Our ipython packages don’t need nose anymore.

**Comment by hroncok** [comment]
> https://build.opensuse.org/package/view_file/devel:languages:python:jupyter/python-ipython_genutils/denose.patch?expand=1 works still just fine for us.

This runs fewer tests (16+1 skip -> 11+1 skip).

I get:

```
ipython_genutils/tests/test_path.py:33: PytestCollectionWarning: cannot collect test class 'TestLinkOrCopy' because it has a __init__ constructor (from: ipython_genutils/tests/test_path.py)
```

This fixes it:

```patch
diff --git a/ipython_genutils/tests/test_path.py b/ipython_genutils/tests/test_path.py
index cecabc6..0f1a0bb 100644
--- a/ipython_genutils/tests/test_path.py
+++ b/ipython_genutils/tests/test_path.py
@@ -31,17 +31,13 @@ def test_ensure_dir_exists():
 
 
 class TestLinkOrCopy(object):
-    def __init__(self):
-        self.tempdir = None
-        self.src = None
-
-    def setUp(self):
+    def setup_method(self):
         self.tempdir = tempfile.TemporaryDirectory()
         self.src = self.dst("src")
         with open(self.src, "w") as f:
             f.write("Hello, world!")
 
-    def tearDown(self):
+    def teardown_method(self):
         self.tempdir.cleanup()
 
     def dst(self, *args):
```

**Comment by Carreau** [comment]
Which package are you using which _depends_ in ipython_genutil ? it is likely it is still mark as a dependency but should not be for ~7 years.

**Comment by mcepl** [comment]
* https://github.com/matplotlib/ipympl, but it may get fixed as well soon (https://github.com/matplotlib/ipympl/commit/564cf6d6767667743cf0e79b0b9a3670feb75c7c).
* https://github.com/jupyter/nbclassic and there the dependency is doing just fine, apparently.

**Comment by Carreau** [comment]
It looks like sage and spyder (in a vendored dependency that needs update) still reference it.

**Comment by Carreau** [comment]
```
$ conda repoquery whoneeds  -c conda-forge ipython_genutils
```

Can help find the current _conda_ packages that list ipytho_genutils as a dependency; it is worth looking as wether they are actual dependencies, and wether the latest versions still use it.
